### ISSUE TITLE
delete button on the result page？

### ISSUE THREAD

**Issue by uqiu** [happiness86/references-plus#2]
![图片](https://github.com/happiness86/references-plus/assets/25265788/fbf357fb-e324-413a-af16-fc9e599d0cda)

https://github.com/alefragnani/vscode-bookmarks

Is it possible to add a delete button on the result page? 
The screenshot is from the BOOKMARK extension.

**Comment by happiness86** [comment]
Actually, I also wanted to add this feature!!!

**Comment by happiness86** [comment]
I have just added this feature, now you can update your extension and have a try😎

**Comment by uqiu** [comment]
seems like it's not working on my end. 😭

**Comment by happiness86** [comment]
It might be useful to restart vscode

**Comment by uqiu** [comment]
still not work.
Can the logs be output to VSCODE's OUTPUT?   I'd like to check the logs.

**Comment by happiness86** [comment]
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()
![Uploading FACBA39B-5B60-40B7-9A11-23EED6875921.png…]()

**Comment by happiness86** [comment]
![image](https://github.com/happiness86/references-plus/assets/26568750/f82cb8ea-1efe-4627-b48b-9dd652141cf1)

**Comment by uqiu** [comment]
`2024-05-27 20:23:05.783 [info] Extension host with pid 222174 started
2024-05-27 20:23:05.800 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/679b43345d427f53f44cb8aec58b6fbc/vscode.lock': Lock acquired.
2024-05-27 20:23:05.950 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-05-27 20:23:05.952 [info] ExtensionService#_doActivateExtension mechatroner.rainbow-csv, startup: false, activationEvent: 'onLanguage:plaintext'
2024-05-27 20:23:05.954 [info] ExtensionService#_doActivateExtension golang.go, startup: false, activationEvent: 'onLanguage:go'
2024-05-27 20:23:06.252 [info] ExtensionService#_doActivateExtension vscode.tunnel-forwarding, startup: false, activationEvent: 'onTunnel'
2024-05-27 20:23:06.960 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-05-27 20:23:06.962 [info] ExtensionService#_doActivateExtension redhat.vscode-yaml, startup: true, activationEvent: '*', root cause: 42Crunch.vscode-openapi
2024-05-27 20:23:06.963 [info] ExtensionService#_doActivateExtension hansu.git-graph-2, startup: true, activationEvent: '*'
2024-05-27 20:23:06.963 [info] ExtensionService#_doActivateExtension outofsync42.select-compare-tabs, startup: true, activationEvent: '*'
2024-05-27 20:23:07.350 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-05-27 20:23:07.351 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-05-27 20:23:08.078 [info] ExtensionService#_doActivateExtension 42Crunch.vscode-openapi, startup: true, activationEvent: '*'
2024-05-27 20:23:09.304 [info] Eager extensions activated
2024-05-27 20:23:09.304 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:09.305 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:09.305 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:09.306 [info] ExtensionService#_doActivateExtension GitHub.copilot, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:09.306 [info] ExtensionService#_doActivateExtension GitHub.copilot-chat, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:09.306 [info] ExtensionService#_doActivateExtension happiness86.vscode-references-plus, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:09.317 [info] ExtensionService#_doActivateExtension maptz.regionfolder, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:12.463 [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 20:23:12.859 [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
2024-05-27 20:23:12.900 [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
2024-05-27 20:23:14.131 [error] [golang.go] provider FAILED
2024-05-27 20:23:14.143 [error] Error: semantictokens are disabled
    at handleResponse (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8606:40)
    at handleMessage (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8416:11)
    at processMessageQueue (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8431:13)
    at Immediate.<anonymous> (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8407:11)
    at processImmediate (node:internal/timers:476:21)
2024-05-27 20:23:15.045 [error] [golang.go] provider FAILED
2024-05-27 20:23:15.045 [error] Error: semantictokens are disabled
    at handleResponse (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8606:40)
    at handleMessage (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8416:11)
    at processMessageQueue (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8431:13)
    at Immediate.<anonymous> (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8407:11)
    at processImmediate (node:internal/timers:476:21)
2024-05-27 20:23:32.875 [error] [golang.go] provider FAILED
2024-05-27 20:23:32.877 [error] Error: semantictokens are disabled
    at handleResponse (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8606:40)
    at handleMessage (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8416:11)
    at processMessageQueue (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8431:13)
    at Immediate.<anonymous> (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8407:11)
    at processImmediate (node:internal/timers:476:21)
2024-05-27 20:24:22.765 [error] [golang.go] provider FAILED
2024-05-27 20:24:22.767 [error] Error: semantictokens are disabled
    at handleResponse (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8606:40)
    at handleMessage (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8416:11)
    at processMessageQueue (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8431:13)
    at Immediate.<anonymous> (/root/.vscode-server/extensions/golang.go-0.41.2/dist/goMain.js:8407:11)
    at processImmediate (node:internal/timers:476:21)
`

is this help?
btw,i use vscode with wsl2.

**Comment by happiness86** [comment]
It looks nothing wrong with the extension. Have you updated the extension to v0.0.9 and reopened vscode?
RP works perfect on my end.
![image](https://github.com/happiness86/references-plus/assets/26568750/8514f425-276a-48cd-ab1e-9582f2c33b60)

**Comment by uqiu** [comment]
```
2024-05-27 20:44:40.847 [error] TypeError: Cannot read properties of undefined (reading 'id')
    at /root/.vscode-server/extensions/happiness86.vscode-references-plus-0.0.9/dist/index.js:184:36
    at d.h (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:141:140094)
    at d.$executeContributedCommand (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:141:140954)
    at u.S (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:150:10829)
    at u.Q (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:150:10595)
    at u.M (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:150:9685)
    at u.L (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:150:8903)
    at f.value (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:150:7567)
    at n.y (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at o.fire (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
    at f.value (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:171:7903)
    at n.y (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at o.fire (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
    at d.z (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:103:17104)
    at f.value (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:103:15556)
    at n.y (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at f.acceptChunk (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:103:11813)
    at f.value (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:103:11100)
    at n.y (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at n.z (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:168:19527)
    at n.acceptFrame (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:168:19333)
    at i.n (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:168:17832)
    at /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:168:15052
    at Socket.E (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:168:12957)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) references-plus.deleteEntry {"value":"happiness86.vscode-references-plus","_lower":"happiness86.vscode-references-plus"}
```

now get this.
I'm not sure if it's related to my use of WSL.
I've tested it in a Windows environment and there's no problem, but when I operate through the extension into WSL, the delete button cannot be activated.

**Comment by uqiu** [comment]
![图片](https://github.com/happiness86/references-plus/assets/25265788/5150eafb-19d8-46c5-adc0-3edc616dd283)
and this

**Comment by happiness86** [comment]
I'm sorry that I don't have a wsl2 environment. It seems that the error is caused by the version I have just published.

**Comment by happiness86** [comment]
I will try to solve this problem, but i can't promise that😅

**Comment by mannfuri** [comment]
![image](https://github.com/happiness86/references-plus/assets/91338215/51e71d43-d115-4750-abf3-14b951a1763a)
I tried it on my home computer and it's working fine now.
Please allow me to test it on the company's computer tomorrow.
However, there's one thing, currently, using my home computer, Only the delete buttons for the two results at the bottom are functional, the delete buttons for the two collapsible items at the top are not responding.

**Comment by uqiu** [comment]
![image](https://github.com/happiness86/references-plus/assets/25265788/4a4d2224-eb3f-44e9-8010-1fa4e04848c3)

I tried it on my home computer(also wsl) and it's working fine now.
Please allow me to test it on the company's computer tomorrow.
However, there's one thing, currently, using my home computer, Only the delete buttons for the two results at the bottom are functional, the delete buttons for the two collapsible items at the top are not responding.

**Comment by happiness86** [comment]
I have noticed this problem too.I will fix it today and release a new version.

**Comment by uqiu** [comment]
I switched to a different WSL distribution, and now it's working properly.
ubuntu 22.04 -> ubuntu 24.04

**Comment by uqiu** [comment]
I think I've found the problem.
The path of my project's directory contains an underscore (_).
I've tested a few projects, and if the project's file path contains an underscore, the delete button cannot be used.
If I remove this underscore, I can delete normally.
I've tested it, and this issue also occurs on WINDOWS.

**Comment by happiness86** [comment]
> I think I've found the problem. The path of my project's directory contains an underscore (_)

I've published a new version to fixed this error. This error is caused by unique id of tree node . I simply use underscore(_) to generate id. This is my fault, thank you so much to help me find this error.

**Comment by uqiu** [comment]
![图片](https://github.com/happiness86/references-plus/assets/25265788/4354d3ec-2d25-4830-be26-5448d8c4e368)

May I ask, did you keep this blank space for the convenience of viewing the code hierarchy?
Have you considered creating a switch to control the display of this blank space?

**Comment by happiness86** [comment]
> Have you considered creating a switch to control the display of this blank space?

Actually, I didn't think too much when I created  this tool. I just didn't handle the blank space. 

This is a good advice. And I will also add some other configuration, such as maximum items in result view.

**Comment by uqiu** [comment]
if I have time, I'll try to tweak the UI with chatgpt to make it more consistent with the overall VS Code UI, and submit a PR.
